version: "3.8"
services:
  app:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: app_container
    hostname: app_server
    volumes:
      - ./backend:/work
      - ./infra/php/:/var/phpapp/
      - ./infra/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  web:
    image: nginx:1.18-alpine
    container_name: web_container
    hostname: web_server
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build:
      context: ./infra/mysql
      dockerfile: Dockerfile
    container_name: db_container
    hostname: db_server
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
